# Generated by Django 4.2.5 on 2023-10-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_pythonproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='image',
            field=models.ImageField(max_length=500, upload_to='education_images/'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='diplome_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='diplomes/'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='photo',
            field=models.ImageField(max_length=500, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='pythonproject',
            name='readme_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='certificate_image',
            field=models.ImageField(max_length=500, upload_to='skill_images/'),
        ),
    ]
